#!/bin/bash
apt-get autoremove -y
/usr/sbin/useradd -s /sbin/nologin -U -d /home/fos-streaming -m fosstreaming
cd /; git clone --recurse-submodules https://github.com/theraw/fospackv69.git; cp -a /fospackv69/fos /home/fos-streaming/; cd /fospackv69/nginx-builder; bash build.sh; cd /; rm -rf /fospackv69
rm -rf /home/fos-streaming/fos/www/vendor /home/fos-streaming/fos/www/50x.html
cd /home/fos-streaming/fos/www; git clone https://github.com/theraw/FOS-Streaming-v69.git
cp -R /home/fos-streaming/fos/www/FOS-Streaming-v69/* /home/fos-streaming/fos/www/; rm -Rf /home/fos-streaming/fos/www/FOS-Streaming-v69/
chown -R nginx:nginx /home/fos-streaming/fos/www; chown -R nginx:nginx /home/fos-streaming/fos/www/*;
echo 'nginx ALL = (root) NOPASSWD: /usr/local/bin/ffmpeg' >> /etc/sudoers
echo 'nginx ALL = (root) NOPASSWD: /usr/local/bin/ffprobe' >> /etc/sudoers
sed --in-place '/exit 0/d' /etc/rc.local
echo '/home/fos-streaming/fos/nginx/sbin/nginx_fos' >> /etc/rc.local
echo '/etc/init.d/php7.3-fpm start' >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local
mkdir -p /home/fos-streaming/fos/www/hl ; chmod -R 777 /home/fos-streaming/fos/www/hl; mkdir -p /home/fos-streaming/fos/www/cache; chmod -R 777 /home/fos-streaming/fos/www/cache; chown nginx:nginx /home/fos-streaming/fos/nginx/conf
curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/improvement/nginx.conf > /home/fos-streaming/fos/nginx/conf/nginx.conf
curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/improvement/php73.conf > /etc/php/7.3/fpm/pool.d/www.conf
wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -O /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz
tar -xJf /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz -C /tmp/; rm -Rf /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz
/bin/cp /tmp/ffmpeg*/ffmpeg  /usr/local/bin/ffmpeg
/bin/cp /tmp/ffmpeg*/ffprobe /usr/local/bin/ffprobe
chmod 755 /usr/local/bin/ffmpeg
chmod 755 /usr/local/bin/ffprobe
echo "`date +%s | sha256sum | base64 | head -c 32 ; echo`" > /root/MYSQL_ROOT_PASSWORD
sqlpasswd=(`cat /root/MYSQL_ROOT_PASSWORD`);
echo "mysql-server mysql-server/root_password password $sqlpasswd" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none" | debconf-set-selections
apt-get -y install mysql-server mysql-client; service mysql stop; service mysql start
mysql -uroot -p$sqlpasswd -e "CREATE DATABASE fos"
mysql -uroot -p$sqlpasswd -e "grant all privileges on fos.* to 'fos'@'localhost' identified by '$sqlpasswd'"
sed -i 's/xxx/fos/g' /home/fos-streaming/fos/www/config.php
sed -i 's/zzz/'$sqlpasswd'/g' /home/fos-streaming/fos/www/config.php
sed -i 's/ttt/fos/g' /home/fos-streaming/fos/www/config.php
mkdir -p /home/fos-streaming/fos/www1/; mkdir -p /home/fos-streaming/fos/www1/log/; chown nginx:nginx /home/fos-streaming/fos/www1/log/; cp -R /home/fos-streaming/fos/www/* /home/fos-streaming/fos/www1/; rm -rf /home/fos-streaming/fos/www1/*.*
rm -rf /home/fos-streaming/fos/www1/hl
ln -s /home/fos-streaming/fos/www/hl /home/fos-streaming/fos/www1/hl
ln -s /home/fos-streaming/fos/www/config.php /home/fos-streaming/fos/www1/config.php
ln -s /home/fos-streaming/fos/www/functions.php /home/fos-streaming/fos/www1/functions.php
ln -s /home/fos-streaming/fos/www/stream.php /home/fos-streaming/fos/www1/stream.php
ln -s /home/fos-streaming/fos/www/playlist.php /home/fos-streaming/fos/www1/playlist.php
ln -sf /etc/alternatives/php /home/fos-streaming/fos/php/bin/php
service php7.3-fpm stop
service php7.3-fpm start
/home/fos-streaming/fos/nginx/sbin/nginx_fos
curl -s http://127.0.0.1:7777/install_database_tables.php?install
curl -s http://127.0.0.1:7777/install_database_tables.php?update
rm -rf /home/fos-streaming/fos/www/install_database_tables.php
